language: ruby

rvm:
  - 1.9.3

before_install:
  - gem update --system

before_script:
  - mysql -e 'create database `powerdns-spec`;'
  - mysql powerdns_spec < misc/powerdns.mysql
  - cp config/database.rb.travis config/database.rb

#script: "bundle exec rake"

gemfile:
  - Gemfile

branches:
  only:
    - master
